phrase:
  project_id: 1f7c2845a714d4ac9929269ce3ed5513
  push:
    sources:
    - file: ./Users/domenicabarone/Downloads/<locale_name>.properties
      params:
        file_format: properties
        locale_id: 85f80d758902bbb45e5d6538349c5b8f
        file_encoding: UTF-8
        autotranslate: true
        format_options:
          escape_single_quotes: false
          escape_meta_chars: false
  pull:
    targets:
    - file: ./Users/domenicabarone/Downloads/<locale_name>.properties
      params:
        file_format: properties
        locale_id: 85f80d758902bbb45e5d6538349c5b8f
        encoding: UTF-8
        include_unverified_translations: true
        format_options:
          escape_single_quotes: false
